// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWPH3phFx0Z7N-wdljgzLmqRTocJC6YI',
    appId: '1:744880037983:web:fb5f0c7b913774e3047bea',
    messagingSenderId: '744880037983',
    projectId: 'floresjrs-b6d5e',
    authDomain: 'floresjrs-b6d5e.firebaseapp.com',
    storageBucket: 'floresjrs-b6d5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAumaI2RUBABHcF8JXDii3fZEdgzvXWlzI',
    appId: '1:744880037983:android:2d4fa6a9e58f8dd2047bea',
    messagingSenderId: '744880037983',
    projectId: 'floresjrs-b6d5e',
    storageBucket: 'floresjrs-b6d5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFgoD6YHV2RjAOdDG-ryoXoGhzJgoNTk',
    appId: '1:744880037983:ios:f624bde02bc7ec74047bea',
    messagingSenderId: '744880037983',
    projectId: 'floresjrs-b6d5e',
    storageBucket: 'floresjrs-b6d5e.firebasestorage.app',
    iosBundleId: 'com.example.floresJrs',
  );
}
